const AUTHORIZATION_FAILED = 401;
const AUTHORIZATION_INVALID = 403;
const INTERNAL_SERVER_ERROR = 500;
const PARAMS_ERROR = 1001;


module.exports = {
    AUTHORIZATION_FAILED,
    AUTHORIZATION_INVALID,
    INTERNAL_SERVER_ERROR,
    PARAMS_ERROR,
}